version: '3.8'

services:
  db:
    build:
      context: src/main/docker/database_files
      dockerfile: multidb_postgres.dockerfile
    image: multiuser/postgres
    ports:
      - "6969:5432"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_MULTIPLE_DATABASES=db_duck,duck,duck;
      - TARGET_DB=db_duck
      - PGDATA=/data/postgres
    volumes:
      - pgdata_duck:/data/postgres
    container_name: database
    
#  back:
#    build:
#      context: .
#      dockerfile: src/main/docker/yan.dockerfile
#    image: duck/api-bot
#    ports:
#      - "9999:8080"
#    environment:
#      - FRONTEND_URL=http://localhost:4200
#      - KEYCLOACK_URL=
#      - KEYCLOACK_SECRET=
#      - KEYCLOACK_CLIENTID=
#    container_name: duck_api
#    depends_on:
#      - db

volumes:
  pgdata_duck:
    external: true
