pipeline {
    agent any

    tools('Configurando Ferramentas') {
        maven 'Maven Jenkins'
    }

    stages {
        stage('Checkout') {
            steps {
                // Limpa o Workspace
                cleanWs()
                sh "echo Clonando a branch selecionada '${GIT_BRANCH}'"
                sh "GIT_BRANCH=${GIT_BRANCH//origin\//}"
                // Baixa o codigo
                git branch: "${GIT_BRANCH}", url: 'https://github.com/yanpgabriel/DuckApi.git'
            }
        }
        stage('Build') {
            steps {
                // Roda o maven
                sh "mvn clean package ${MAVEN_ARGS}"
            }
        }
    }
}
