pipeline {
    agent any

    tools('Configurando Ferramentas') {
        maven 'Maven Jenkins'
    }

    stages {
        stage('Checkout') {
            steps {
                // Limpa o Workspace
                cleanWs()
                sh "echo Clonando a branch selecionada '${BRANCH_TO_DEPLOY}'"
                // Baixa o codigo
                git branch: "${BRANCH_TO_DEPLOY}", url: 'https://github.com/yanpgabriel/DuckApi.git'
            }
        }
        stage('Build') {
            steps {
                // Roda o maven
                sh "mvn clean package ${MAVEN_ARGS}"
            }
        }
        stage('Arquivar artefato') {
            steps {
                archiveArtifacts allowEmptyArchive: true, artifacts: 'target/*-SNAPSHOT.jar', followSymlinks: false, onlyIfSuccessful: true
            }
        }
    }
}
