pipeline {
    agent any

    parameters{
        gitParameter(name: 'BRANCH_TO_DEPLOY', branch: '', branchFilter: 'origin/(.*)', defaultValue: 'develop',
        quickFilterEnabled: false, selectedValue: 'NONE', sortMode: 'NONE', tagFilter: '*',
        type: 'GitParameterDefinition', useRepository: 'https://github.com/yanpgabriel/DuckApi.git')

        string(name: 'MAVEN_ARGS', defaultValue: '-DskipTests', trim: true)
        string(name: 'DOCKER_IMAGE', defaultValue: 'localhost:5000/duckapi-jvm:pi', trim: true)
    }

    tools('Configurando Ferramentas') {
        maven 'Maven Jenkins'
        // dockerTool 'Docker Jenkins'
    }

    environment {
        GIT_HASH = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
        COMMITER_NAME = sh(script: 'git show -s --pretty=%an', returnStdout: true).trim()
        COMMITER_EMAIL = sh(script: 'git show -s --format=%ae', returnStdout: true).trim()
        COMMITER_COMMENT = sh(script: 'git show -s --pretty=%B', returnStdout: true).trim()

        NAMESPACE = 'duck-namespace'
    }

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds(abortPrevious: true)
    }

    stages {
        stage('Checkout') {
            steps {
                // Limpa o Workspace
                cleanWs()
                sh "echo ${GIT_HASH}"
                sh "echo ${COMMITER_NAME}"
                sh "echo ${COMMITER_EMAIL}"
                sh "echo ${COMMITER_COMMENT}"
                sh "echo ${NAMESPACE}"
                sh "echo ---"
                sh "echo Clonando a branch selecionada '${BRANCH_TO_DEPLOY}'"
                // Baixa o codigo
                git branch: "${BRANCH_TO_DEPLOY}", url: 'https://github.com/yanpgabriel/DuckApi.git'
            }
        }
        stage('Build') {
            steps {
                configFileProvider([configFile(fileId: 'a4023191-d4f8-4d46-a517-48515779be66', targetLocation: './')]) {
                    // Roda o maven
                    sh "mvn clean package ${MAVEN_ARGS}"
                }
            }
        }
        stage('Arquivar artefato') {
            steps {
                archiveArtifacts allowEmptyArchive: true, artifacts: 'target/*-SNAPSHOT.jar', followSymlinks: false, onlyIfSuccessful: true
            }
        }
        stage('Gerar Imagem Docker') {
            steps {
                sh "docker build -f src/main/docker/yan.dockerfile -t ${DOCKER_IMAGE} ."
            }
        }
        stage('Publicar Imagem Docker') {
            steps {
                sh "docker push ${DOCKER_IMAGE}"
            }
        }
    }
}
