apiVersion: v1
kind: Namespace
metadata:
  name: duck-namespace
  labels:
    name: duck-namespace

---

apiVersion: v1
kind: Pod
metadata:
  name: duck-api
  namespace: duck-namespace
  labels:
    app: duck-api
spec:
  containers:
    - name: duck-api
      image: rasp.local:500/duckapi-jvm
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: duck-cm-env
  restartPolicy: Never
